### ISSUE TITLE
php 7.3 / openssl 1.1.1 segfault

### ISSUE THREAD

**Issue by zbskii** [oerdnj/deb.sury.org#1030]
php7.3 installed on ubuntu 16.04 from ppa:ondrej/php:
```
ii  libapache2-mod-php7.3         7.3.0-2+ubuntu16.04.1+deb.sury.org+1                    amd64        server-side, HTML-embedded scripting language (Apache 2 module)
ii  php7.3-bcmath                 7.3.0-2+ubuntu16.04.1+deb.sury.org+1                    amd64        Bcmath module for PHP
ii  php7.3-cli                    7.3.0-2+ubuntu16.04.1+deb.sury.org+1                    amd64        command-line interpreter for the PHP scripting language
ii  php7.3-common                 7.3.0-2+ubuntu16.04.1+deb.sury.org+1                    amd64        documentation, examples and common module for PHP
ii  php7.3-curl                   7.3.0-2+ubuntu16.04.1+deb.sury.org+1                    amd64        CURL module for PHP
ii  php7.3-gd                     7.3.0-2+ubuntu16.04.1+deb.sury.org+1                    amd64        GD module for PHP
ii  php7.3-gmp                    7.3.0-2+ubuntu16.04.1+deb.sury.org+1                    amd64        GMP module for PHP
ii  php7.3-intl                   7.3.0-2+ubuntu16.04.1+deb.sury.org+1                    amd64        Internationalisation module for PHP
ii  php7.3-json                   7.3.0-2+ubuntu16.04.1+deb.sury.org+1                    amd64        JSON module for PHP
ii  php7.3-mbstring               7.3.0-2+ubuntu16.04.1+deb.sury.org+1                    amd64        MBSTRING module for PHP
ii  php7.3-mysql                  7.3.0-2+ubuntu16.04.1+deb.sury.org+1                    amd64        MySQL module for PHP
ii  php7.3-odbc                   7.3.0-2+ubuntu16.04.1+deb.sury.org+1                    amd64        ODBC module for PHP
ii  php7.3-opcache                7.3.0-2+ubuntu16.04.1+deb.sury.org+1                    amd64        Zend OpCache module for PHP
ii  php7.3-readline               7.3.0-2+ubuntu16.04.1+deb.sury.org+1                    amd64        readline module for PHP
ii  php7.3-xml                    7.3.0-2+ubuntu16.04.1+deb.sury.org+1                    amd64        DOM, SimpleXML, WDDX, XML, and XSL module for PHP
ii  php7.3-xsl                    7.3.0-2+ubuntu16.04.1+deb.sury.org+1                    all          XSL module for PHP (dummy)
ii  php7.3-zip                    7.3.0-2+ubuntu16.04.1+deb.sury.org+1                    amd64        Zip module for PHP
```
openssl:
```i  openssl                       1.1.1-1+ubuntu16.04.1+deb.sury.org+1                    amd64        Secure Sockets Layer toolkit - cryptographic utility```

The following php script will cause a coredump:
```
$pk = openssl_pkey_new(["private_key_bits" => 384]);
$key = openssl_pkey_get_details($pk);
```

```Core was generated by `php -a'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f1b2298bc99 in BN_num_bits () from /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1
(gdb) bt
#0  0x00007f1b2298bc99 in BN_num_bits () from /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1
#1  0x00005592d9e44ceb in ?? ()
#2  0x00005592da03a3ee in execute_ex ()
#3  0x00005592da04303a in zend_execute ()
#4  0x00005592d9fa6096 in zend_eval_stringl ()
#5  0x00007f1b139f5faf in ?? () from /usr/lib/php/20180731/readline.so
#6  0x00005592da0452a5 in ?? ()
#7  0x00005592d9e0d7ec in ?? ()
#8  0x00007f1b22052830 in __libc_start_main (main=0x5592d9e0d370, argc=2, argv=0x7ffd803546c8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7ffd803546b8) at ../csu/libc-start.c:291
#9  0x00005592d9e0d909 in _start ()```

**Comment by oerdnj** [comment]
Please report this to bugs.php.net, it's not related to the packaging.
