### ISSUE TITLE
php5.6 for Ubuntu 14.04 LTS no more available?

### ISSUE THREAD

**Issue by mikeyea22** [oerdnj/deb.sury.org#1044]
Hello,

I am trying to update php5.5.9 on 14.04 LTS into php 5.6 by doing 
>add-apt-repository ppa:ondrej/php 

but I get errors like so:

> Traceback (most recent call last):
  File "/usr/bin/add-apt-repository", line 163, in <module>
    if not sp.add_source_from_shortcut(shortcut, options.enable_source):
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 750, in add_source_from_shortcut
    self.set_modified_sourceslist()
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 484, in set_modified_sourceslist
    self.save_sourceslist()
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 650, in save_sourceslist
    self.sourceslist.save()
  File "/usr/lib/python3/dist-packages/aptsources/sourceslist.py", line 415, in save
    files[source.file] = open(source.file, "w")
FileNotFoundError: [Errno 2] No such file or directory: '/etc/apt/sources.list.d/ondrej-php-trusty.list'

Is this a python problem or is the PPA not supporting 14.04 LTS anymore?

Thanks for help
Mike

**Comment by todeveni** [comment]
Works for me on a clean Trusty image.

Running as root:
`LC_ALL=C.UTF-8 add-apt-repository ppa:ondrej/php`

**Comment by antoinekociuba** [comment]
Hi here, it seems that support for 14.04 has been totally dropped, since 14.04 has reached its EOL.
I do not know how to find an alternative so far, but actively looking for something...
Any help/tips/clue will be much appreciated. :)

**Comment by janisbiz** [comment]
@antoinekociuba same here. I can't even find any old build package for trusty. It's really a pity, that everything is gone barely one year EOL.
