### ISSUE TITLE
php-raphf and PHP 5.6 - SIGSEGV

### ISSUE THREAD

**Issue by JSkalskiSBG** [oerdnj/deb.sury.org#1066]
**Describe the bug**
```phpinfo()``` crashes when module 'php-raphf' is enabled. Core dump with xdebug disabled:
```
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `php5.6 info.php'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x000055a773bfaef5 in ?? ()
(gdb) bt full
#0  0x000055a773bfaef5 in ?? ()
No symbol table info available.
#1  0x000055a773bfb990 in php_info_print_table_row ()
No symbol table info available.
#2  0x00007f5f8387b61d in zm_info_http () from /usr/lib/php/20131226/http.so
No symbol table info available.
#3  0x000055a773bfbab0 in ?? ()
No symbol table info available.
#4  0x000055a773cb8cbb in zend_hash_apply ()
No symbol table info available.
#5  0x000055a773bfc592 in php_print_info ()
No symbol table info available.
#6  0x000055a773bfcb14 in zif_phpinfo ()
No symbol table info available.
#7  0x000055a773c9915a in dtrace_execute_internal ()
No symbol table info available.
#8  0x000055a773d5793f in ?? ()
No symbol table info available.
#9  0x000055a773ce77d0 in execute_ex ()
No symbol table info available.
#10 0x000055a773c99006 in dtrace_execute_ex ()
No symbol table info available.
#11 0x000055a773cab9eb in zend_execute_scripts ()
No symbol table info available.
#12 0x000055a773c47d90 in php_execute_script ()
No symbol table info available.
#13 0x000055a773d599ed in ?? ()
No symbol table info available.
#14 0x000055a773b1f160 in main ()
No symbol table info available.
```

**To Reproduce**
0. Install Linux Mint 19 (based on Ubuntu 18.04)
1. Install a lot of packages of all available versions of PHP to prepare dev environment.
Code I executed and order in which I installed (7.2, 7.3, 7.1, 7.0, 5.6):
```
apt install php7.2 php7.2-fpm php7.2-bcmath php7.2-bz2 php7.2-calendar php7.2-cli php7.2-common php7.2-ctype php7.2-curl php7.2-dba php7.2-dev php7.2-dom php7.2-exif php7.2-fileinfo php7.2-gd php7.2-gettext php7.2-gmp php7.2-http php7.2-iconv php7.2-imagick php7.2-intl php7.2-json php7.2-ldap php7.2-mailparse php7.2-mbstring php7.2-mongodb php7.2-mysql php7.2-mysqli php7.2-mysqlnd php7.2-oauth php7.2-odbc php7.2-opcache php7.2-pdo php7.2-pdo-dblib php7.2-pdo-mysql php7.2-pdo-odbc php7.2-pdo-pgsql php7.2-pdo-sqlite php7.2-pgsql php7.2-phar php7.2-phpdbg php7.2-posix php7.2-radius php7.2-readline php7.2-redis php7.2-simplexml php7.2-smbclient php7.2-soap php7.2-sockets php7.2-solr php7.2-sqlite3 php7.2-ssh2 php7.2-sybase php7.2-tokenizer php7.2-uploadprogress php7.2-uuid php7.2-xdebug php7.2-xml php7.2-xmlreader php7.2-xmlrpc php7.2-xmlwriter php7.2-yaml php7.2-zip

apt install php7.3 php7.3-fpm php7.3-bcmath php7.3-bz2 php7.3-calendar php7.3-cli php7.3-common php7.3-ctype php7.3-curl php7.3-dba php7.3-dev php7.3-dom php7.3-exif php7.3-fileinfo php7.3-gd php7.3-gettext php7.3-gmp php7.3-http php7.3-iconv php7.3-imagick php7.3-intl php7.3-json php7.3-ldap php7.3-mailparse php7.3-mbstring php7.3-mongodb php7.3-mysql php7.3-mysqli php7.3-mysqlnd php7.3-oauth php7.3-odbc php7.3-opcache php7.3-pdo php7.3-pdo-dblib php7.3-pdo-mysql php7.3-pdo-odbc php7.3-pdo-pgsql php7.3-pdo-sqlite php7.3-pgsql php7.3-phar php7.3-phpdbg php7.3-posix php7.3-radius php7.3-readline php7.3-redis php7.3-simplexml php7.3-smbclient php7.3-soap php7.3-sockets php7.3-solr php7.3-sqlite3 php7.3-ssh2 php7.3-sybase php7.3-tokenizer php7.3-uploadprogress php7.3-uuid php7.3-xdebug php7.3-xml php7.3-xmlreader php7.3-xmlrpc php7.3-xmlwriter php7.3-yaml php7.3-zip

apt install php7.1 php7.1-fpm php7.1-bcmath php7.1-bz2 php7.1-calendar php7.1-cli php7.1-common php7.1-ctype php7.1-curl php7.1-dba php7.1-dev php7.1-dom php7.1-exif php7.1-fileinfo php7.1-gd php7.1-gettext php7.1-gmp php7.1-http php7.1-iconv php7.1-imagick php7.1-intl php7.1-json php7.1-ldap php7.1-mailparse php7.1-mbstring php7.1-mongodb php7.1-mysql php7.1-mysqli php7.1-mysqlnd php7.1-oauth php7.1-odbc php7.1-opcache php7.1-pdo php7.1-pdo-dblib php7.1-pdo-mysql php7.1-pdo-odbc php7.1-pdo-pgsql php7.1-pdo-sqlite php7.1-pgsql php7.1-phar php7.1-phpdbg php7.1-posix php7.1-radius php7.1-readline php7.1-redis php7.1-simplexml php7.1-smbclient php7.1-soap php7.1-sockets php7.1-solr php7.1-sqlite3 php7.1-ssh2 php7.1-sybase php7.1-tokenizer php7.1-uploadprogress php7.1-uuid php7.1-xdebug php7.1-xml php7.1-xmlreader php7.1-xmlrpc php7.1-xmlwriter php7.1-yaml php7.1-zip

apt install php7.0 php7.0-fpm php7.0-bcmath php7.0-bz2 php7.0-calendar php7.0-cli php7.0-common php7.0-ctype php7.0-curl php7.0-dba php7.0-dev php7.0-dom php7.0-exif php7.0-fileinfo php7.0-gd php7.0-gettext php7.0-gmp php7.0-http php7.0-iconv php7.0-imagick php7.0-intl php7.0-json php7.0-ldap php7.0-mailparse php7.0-mbstring php7.0-mongodb php7.0-mysql php7.0-mysqli php7.0-mysqlnd php7.0-oauth php7.0-odbc php7.0-opcache php7.0-pdo php7.0-pdo-dblib php7.0-pdo-mysql php7.0-pdo-odbc php7.0-pdo-pgsql php7.0-pdo-sqlite php7.0-pgsql php7.0-phar php7.0-phpdbg php7.0-posix php7.0-radius php7.0-readline php7.0-redis php7.0-simplexml php7.0-smbclient php7.0-soap php7.0-sockets php7.0-solr php7.0-sqlite3 php7.0-ssh2 php7.0-sybase php7.0-tokenizer php7.0-uploadprogress php7.0-uuid php7.0-xdebug php7.0-xml php7.0-xmlreader php7.0-xmlrpc php7.0-xmlwriter php7.0-yaml php7.0-zip

apt install php5.6 php5.6-fpm php5.6-bcmath php5.6-bz2 php5.6-calendar php5.6-cli php5.6-common php5.6-ctype php5.6-curl php5.6-dba php5.6-dev php5.6-dom php5.6-exif php5.6-fileinfo php5.6-gd php5.6-gettext php5.6-gmp php5.6-http php5.6-iconv php5.6-imagick php5.6-intl php5.6-json php5.6-ldap php5.6-mailparse php5.6-mbstring php5.6-mongodb php5.6-mysql php5.6-mysqli php5.6-mysqlnd php5.6-oauth php5.6-odbc php5.6-opcache php5.6-pdo php5.6-pdo-dblib php5.6-pdo-mysql php5.6-pdo-odbc php5.6-pdo-pgsql php5.6-pdo-sqlite php5.6-pgsql php5.6-phar php5.6-phpdbg php5.6-posix php5.6-radius php5.6-readline php5.6-redis php5.6-simplexml php5.6-smbclient php5.6-soap php5.6-sockets php5.6-solr php5.6-sqlite3 php5.6-ssh2 php5.6-sybase php5.6-tokenizer php5.6-uploadprogress php5.6-uuid php5.6-xdebug php5.6-xml php5.6-xmlreader php5.6-xmlrpc php5.6-xmlwriter php5.6-yaml php5.6-zip
```
There is no 'php-raphf' on list. It was required by one of packages and auto-installed.
2. Make **info.php** file that executes **phpinfo()**
3. Execute it: **php5.6 info.php**
4. See ```Segmentation fault (core dumped)```

**Distribution (please complete the following information):**
 - OS: Linux Mint 19.1 (based on Ubuntu 18.04)
 - Architecture: amd64
 - Repository:  ```deb http://ppa.launchpad.net/ondrej/php/ubuntu bionic main```

**Package(s) (please complete the following information):**
```
php-raphf:
  Installed: 2.0.0+1.1.2-3+ubuntu18.04.1+deb.sury.org+10
  Candidate: 2.0.0+1.1.2-3+ubuntu18.04.1+deb.sury.org+10
  Version table:
 *** 2.0.0+1.1.2-3+ubuntu18.04.1+deb.sury.org+10 500
        500 http://ppa.launchpad.net/ondrej/php/ubuntu bionic/main amd64 Packages
        100 /var/lib/dpkg/status
     2.0.0+1.1.2-2build2 500
        500 http://archive.ubuntu.com/ubuntu bionic/universe amd64 Packages
```

**Additional context**
**php -m** and **php -v** works on 5.6 without problem and display 'raphf' on modules list.
PHP 7.0+ **phpinfo** works and displays **raphf** version 2.0.0

I don't know how version '2.0.0+1.1.2-3' works (2 version at once or what), but on PECL I found that 2.0 is not compatible with PHP 5.6:
https://pecl.php.net/package/raphf

**Comment by oerdnj** [comment]
PHP 5.6 has reached end-of-life. I don’t expect to spend any extra time on it. You should update th at least PHP 7.1.

https://www.patreon.com/posts/ubuntu-14-04-php-22093917

**Comment by oerdnj** [comment]
I will apply important security fixes for PHP 5.6 for a while, but fixing fringe modules hardly seems time usefully spent. Sorry.
