### ISSUE TITLE
Add PPA leads to raspbian buster Error: could not find a distribution template for Raspbian/buster

### ISSUE THREAD

**Issue by blokdk** [oerdnj/deb.sury.org#1246]
I am unable to add your PPA with the proposed commands.
BTW the python checker I seem to need:
sudo apt-get install software-properties-common 
is not mentioned in the FAQ.
 sudo add-apt-repository ppa:ondrej/php
Traceback (most recent call last):
  File "/usr/bin/add-apt-repository", line 95, in <module>
    sp = SoftwareProperties(options=options)
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 109, in __init__
    self.reload_sourceslist()
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 599, in reload_sourceslist
    self.distro.get_sources(self.sourceslist)    
  File "/usr/lib/python3/dist-packages/aptsources/distro.py", line 93, in get_sources
    (self.id, self.codename))
aptsources.distro.NoDistroTemplateException: Error: could not find a distribution template for Raspbian/buster

**Comment by oerdnj** [comment]
https://github.com/oerdnj/deb.sury.org/issues/988

**Comment by blokdk** [comment]
Checked /proc/cpuinfo and it seems I am using a
model name	: ARMv7 Processor rev 4 (v7l)

**Comment by oerdnj** [comment]
Well, you are trying to use Ubuntu PPA on Raspbian. Why do you expect it to work?

**Comment by DMW007** [comment]
Hi, 

it seems even not to work with the correct DPA for Debian:
```bash
pi@testpi:/etc/apache2 $ sudo apt-add-repository packages.sury.org/php
Traceback (most recent call last):
  File "/usr/bin/apt-add-repository", line 95, in <module>
    sp = SoftwareProperties(options=options)
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 109, in __init__
    self.reload_sourceslist()
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 599, in reload_sourceslist
    self.distro.get_sources(self.sourceslist)
  File "/usr/lib/python3/dist-packages/aptsources/distro.py", line 93, in get_sources
    (self.id, self.codename))
aptsources.distro.NoDistroTemplateException: Error: could not find a distribution template for Raspbian/buster

pi@testpi:/etc/apache2 $ sudo apt-add-repository "deb https://packages.sury.org/php/ $(lsb_release -sc) main"
Traceback (most recent call last):
  File "/usr/bin/apt-add-repository", line 95, in <module>
    sp = SoftwareProperties(options=options)
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 109, in __init__
    self.reload_sourceslist()
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 599, in reload_sourceslist
    self.distro.get_sources(self.sourceslist)
  File "/usr/lib/python3/dist-packages/aptsources/distro.py", line 93, in get_sources
    (self.id, self.codename))
aptsources.distro.NoDistroTemplateException: Error: could not find a distribution template for Raspbian/buster

pi@testpi:/etc/apache2 $ lsb_release -sc
buster

pi@testpi:/etc/apache2 $ uname -a
Linux testpi 5.10.63-v7l+ #1457 SMP Tue Sep 28 11:26:14 BST 2021 armv7l GNU/Linux
```
However, the releases file contains both AR architectures `amd64 armhf arm64 i386` and when I add the key manually and the apt list entry like this
```bash
echo "deb https://packages.sury.org/php/ $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/php.list
```
I could install the latest stable PHP 8 release:

```
pi@testpi:/etc/apache2 $ php -v | head -1
PHP 8.0.11 (cli) (built: Sep 23 2021 22:03:11) ( NTS )
```
Also works on Apache2 after replacing the old PHP 7.3 module from the Raspberry Pi OS repos with your new 8.0 one. Do you have an explanation why `apt-add-repository` doesn't let me add your repo? It's a RPI 4 with 32 Bit Raspberry Pi OS. 

Thank you anyway for porting the latest stable PHP versions to a trusty repo, this is something I'm really missing on Debian at all where only the oldest stable version is avaliable :+1 Otherwise it would be a bit frustrating to have an version in the repos where even the extended security support ends in about just 2 months...
