### ISSUE TITLE
Can not  instantiate  http\Client on Ubuntu 18.04 with php5.6-http

### ISSUE THREAD

**Issue by nagyt234** [oerdnj/deb.sury.org#1638]
The simple php program which instantiates http\Client generates an exception on Ubuntu 18:
```
$ cat /tmp/test.php
<?php
      $client = new \http\Client;

$ php /tmp/test.php
PHP Fatal error:  Uncaught exception 'http\Exception\UnexpectedValueException' with message 'Failed to locate "(null)" client request handler' in /tmp/test.php:2
Stack trace:
#0 /tmp/test.php(2): http\Client->__construct()
#1 {main}
  thrown in /tmp/test.php on line 2
```
PHP version:
```
$ php -v
PHP 5.6.40-53+ubuntu18.04.1+deb.sury.org+1 (cli)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
```
Installed php and curl packages:
```
$ dpkg --get-selections | egrep 'php|curl'
libapache2-mod-php5.6                           install
libcurl3:amd64                                  install
libcurl3-gnutls:amd64                           install
php-common                                      install
php-pear                                        install
php5.6                                          install
php5.6-cli                                      install
php5.6-common                                   install
php5.6-dev                                      install
php5.6-http                                     install
php5.6-json                                     install
php5.6-mbstring                                 install
php5.6-mysql                                    install
php5.6-opcache                                  install
php5.6-propro                                   install
php5.6-raphf                                    install
php5.6-readline                                 install
php5.6-xml                                      install
pkg-php-tools                                   install
```
Any idea?

**Comment by sleemanj** [comment]
Sounds like related to https://github.com/oerdnj/deb.sury.org/issues/1442 ---- On Wed, 15 Sep 2021 00:51:41 +1200  ***@***.***  wrote ----
The simple php program which instantiates http\Client generates an exception on Ubuntu 18:
$ cat /tmp/test.php
<?php
      $client = new \http\Client;

$ php /tmp/test.php
PHP Fatal error:  Uncaught exception 'http\Exception\UnexpectedValueException' with message 'Failed to locate "(null)" client request handler' in /tmp/test.php:2
Stack trace:
#0 /tmp/test.php(2): http\Client->__construct()
#1 {main}
  thrown in /tmp/test.php on line 2

PHP version:
$ php -v
PHP 5.6.40-53+ubuntu18.04.1+deb.sury.org+1 (cli)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies

Installed php and curl packages:
$ dpkg --get-selections | egrep 'php|curl'
libapache2-mod-php5.6                           install
libcurl3:amd64                                  install
libcurl3-gnutls:amd64                           install
php-common                                      install
php-pear                                        install
php5.6                                          install
php5.6-cli                                      install
php5.6-common                                   install
php5.6-dev                                      install
php5.6-http                                     install
php5.6-json                                     install
php5.6-mbstring                                 install
php5.6-mysql                                    install
php5.6-opcache                                  install
php5.6-propro                                   install
php5.6-raphf                                    install
php5.6-readline                                 install
php5.6-xml                                      install
pkg-php-tools                                   install

Any idea?

**Comment by oerdnj** [comment]
Folks, you need to stop using PHP versions that reached End-Of-Life years ago and still expect that everything would work and bugs will get fixed. They won't, this is just legacy.

> Any idea?

Upgrade your code to PHP 8.0.

**Comment by nagyt234** [comment]
@oerdnj You are absolutely right. The problem is, that I have to run a legacy system, which works on Ubuntu 16 with PHP 5.6 without any problem, but the operating system must be a supported system because of the company's security policy, so I can not use Ubuntu 16 anymore.

**Comment by oerdnj** [comment]
My only recommendation here would be to try to compile the `raphf`, `propro` and `pecl_http` extensions by hand and see whether you can find a combination of versions that does work.
