### ISSUE TITLE
LC_ALL=C.UTF-8 add-apt-repository ppa:ondrej/php error

### ISSUE THREAD

**Issue by AvinFajarF** [oerdnj/deb.sury.org#1820]
Traceback (most recent call last):
  File "/usr/bin/add-apt-repository", line 95, in <module>
    sp = SoftwareProperties(options=options)
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 103, in __init__
    self.sourceslist = SourcesList()
  File "/usr/lib/python3/dist-packages/aptsources/sourceslist.py", line 276, in __init__
    self.refresh()
  File "/usr/lib/python3/dist-packages/aptsources/sourceslist.py", line 292, in refresh
    self.matcher.match(source)
  File "/usr/lib/python3/dist-packages/aptsources/sourceslist.py", line 484, in match
    if (re.search(template.match_uri, source.uri) and
  File "/usr/lib/python3.9/re.py", line 201, in search
    return _compile(pattern, flags).search(string)
  File "/usr/lib/python3.9/re.py", line 304, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib/python3.9/sre_compile.py", line 764, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/lib/python3.9/sre_parse.py", line 948, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
  File "/usr/lib/python3.9/sre_parse.py", line 443, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
  File "/usr/lib/python3.9/sre_parse.py", line 834, in _parse
    p = _parse_sub(source, state, sub_verbose, nested + 1)
  File "/usr/lib/python3.9/sre_parse.py", line 443, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
  File "/usr/lib/python3.9/sre_parse.py", line 834, in _parse
    p = _parse_sub(source, state, sub_verbose, nested + 1)
  File "/usr/lib/python3.9/sre_parse.py", line 443, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
  File "/usr/lib/python3.9/sre_parse.py", line 668, in _parse
    raise source.error("nothing to repeat",
re.error: nothing to repeat at position 2

how do i fix it?

**Comment by oerdnj** [comment]
You need to report the issue to Ubuntu, this doesn't seem specific to this repository.
