### ISSUE TITLE
php 5.6 on bookwork libevent =>  Segmentation fault

### ISSUE THREAD

**Issue by pschonmann** [oerdnj/deb.sury.org#2017]
**Frequently asked questions**

- [ x] I have read [Frequently Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)
- [ x] I have looked at the list of the existing issues (including closed issues) and searched if my issue has been already reported
- [ x] I have tried to resolve the issue myself and will describe what I did in clear and consise manner

**Describe the bug**
When i run php5.6 -i it crashed, same as php-fpm56 version - there is error 503
remote IP:44644] AH01067: Failed to read FastCGI header
104)Connection reset by peer: [remote IP:44644] AH01075: Error dispatching request to :

**To Reproduce**
1. write in console php5.6 -i
2. echo $? is 139
3. Same as fpm - errors from log described above

**Your understanding of what is happening**
Something is wrong with libraries ? ive installed
ii  libevent-2.1-7:amd64                2.1.12-stable-8                                    amd64        Asynchronous event notification library

here is backtrace

```
Used Library => Compiled => Linked
libz => 1.2.13 => 1.2.13
libcurl => disabled => disabled
libevent =>  
Program received signal SIGSEGV, Segmentation fault.
0x0000555555703e42 in php_info_print_table_row_internal (num_cols=3, value_class=0x55555587fb54 "v", row_elements=0x7fffffffd1d0) at ./ext/standard/info.c:1299
1299	./ext/standard/info.c: No such file or directory.
(gdb) bt
#0  0x0000555555703e42 in php_info_print_table_row_internal (num_cols=3, value_class=0x55555587fb54 "v", row_elements=0x7fffffffd1d0) at ./ext/standard/info.c:1299
#1  0x00005555557049e0 in php_info_print_table_row (num_cols=<optimized out>) at ./ext/standard/info.c:1334
#2  0x00007fffef72ffad in zm_info_http () from /usr/lib/php/20131226/http.so
#3  0x0000555555704b00 in _display_module_info_func (module=<optimized out>) at ./ext/standard/info.c:178
#4  0x00005555557b8034 in zend_hash_apply (ht=ht@entry=0x7fffffffd340, apply_func=apply_func@entry=0x555555704af0 <_display_module_info_func>) at ./Zend/zend_hash.c:641
#5  0x0000555555705354 in php_print_info (flag=-1) at ./ext/standard/info.c:1071
#6  0x000055555584a5a1 in do_cli (argc=2, argv=0x5555559af3f0) at ./sapi/cli/php_cli.c:694
#7  0x0000555555628e3e in main (argc=2, argv=0x5555559af3f0) at ./sapi/cli/php_cli.c:1382

```

**What steps did you take to resolve issue yourself before reporting it here**
apt update && apt upgrade - no new updates

**Expected behavior**
Just works :+1: 

**Distribution (please complete the following information):**
 - OS: Debian 12 - bookworm
 - Architecture: amd64
 - Repository: packages.sury.org

**Package(s) (please complete the following information):**
```
php5.6-cli:
  Installed: 5.6.40-67+0~20230815.79+debian12~1.gbpcb4298
  Candidate: 5.6.40-67+0~20230815.79+debian12~1.gbpcb4298
  Version table:
 *** 5.6.40-67+0~20230815.79+debian12~1.gbpcb4298 500
        500 https://packages.sury.org/php bookworm/main amd64 Packages
        100 /var/lib/dpkg/status
```

**Additional context**
Happy debugging

**Comment by pschonmann** [comment]
Still persist in 
```
php5.6:
  Installed: (none)
  Candidate: 5.6.40-81+0~20241224.91+debian12~1.gbp02231c
  Version table:
     5.6.40-81+0~20241224.91+debian12~1.gbp02231c 500
        500 https://packages.sury.org/php bookworm/main amd64 Packages
```

FPM-PART

```
php5.6-fpm:
  Installed: 5.6.40-81+0~20241224.91+debian12~1.gbp02231c
  Candidate: 5.6.40-81+0~20241224.91+debian12~1.gbp02231c
  Version table:
 *** 5.6.40-81+0~20241224.91+debian12~1.gbp02231c 500
        500 https://packages.sury.org/php bookworm/main amd64 Packages
        100 /var/lib/dpkg/status
```
Here is trace from php5.6-fpm where im loading php info page as index.php

 ```
root@debug-website:~# gdb --args /usr/sbin/php-fpm5.6 --nodaemonize --fpm-config /etc/php/5.6/fpm/php-fpm.conf
GNU gdb (Debian 13.1-3) 13.1
Copyright (C) 2023 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/sbin/php-fpm5.6...
Reading symbols from /usr/lib/debug/.build-id/9b/22483b4927c51c9ed84eb02840b4cc63c035ca.debug...
(gdb) set follow-fork-mode child
(gdb) set detach-on-fork off
(gdb) run
Starting program: /usr/sbin/php-fpm5.6 --nodaemonize --fpm-config /etc/php/5.6/fpm/php-fpm.conf
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[04-Mar-2025 09:48:31] NOTICE: fpm is running, pid 4006539
[Attaching after Thread 0x7ffff7a92480 (LWP 4006539) fork to child process 4006542]
[New inferior 2 (process 4006542)]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Thread 2.1 "php-fpm5.6" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff7a92480 (LWP 4006542)]
0x00005555557039f2 in php_info_print_table_row_internal (Reading symbols from /usr/lib/debug/.build-id/6d/201df2cb50847f0ed42da4158c3a608d578f03.debug...
Reading symbols from /usr/lib/debug/.build-id/c0/47672cae7964324658491e7dee26748ae5d2f8.debug...
Reading symbols from /usr/lib/debug/.build-id/f4/bc47db467906580a47640e01e6d901e2642a7b.debug...
Reading symbols from /usr/lib/debug/.build-id/2b/4bc923c2ffaac5d738edb76ca2046c21a6f23b.debug...
Reading symbols from /usr/lib/debug/.build-id/e9/5f490cff3e10b5412bd9c9497697faefe18d9b.debug...
Reading symbols from /usr/lib/debug/.build-id/e5/815fd30fd73c9d1f0765a9074be1d88a9402fe.debug...
Reading symbols from /usr/lib/debug/.build-id/fd/aa3ad670ae8c224c4002facae544c51f2ae99f.debug...
Reading symbols from /usr/lib/debug/.build-id/86/0162f16e80fa8a42e9898cdbebfba128643c0c.debug...
Reading symbols from /usr/lib/debug/.build-id/fb/4db5e988715b16d1c1ec87fa9e6c2fb5ecbfd8.debug...
Reading symbols from /usr/lib/debug/.build-id/40/1b2c2dee63ea1a0c2a2abd31875ce0ae658feb.debug...
Reading symbols from /usr/lib/debug/.build-id/f1/1347b92855b0e447d0169095d0b1a2be1b9608.debug...
Reading symbols from /usr/lib/debug/.build-id/da/bc00a92f1c3f639681507a25d2644e46f6787b.debug...
Reading symbols from /usr/lib/debug/.build-id/00/035eff10bab01f34ff713536d358ef8b90d377.debug...
Reading symbols from /usr/lib/debug/.build-id/aa/3a409cf56804a84fa61bd6ca06dce9a1539e36.debug...
Reading symbols from /usr/lib/debug/.build-id/8f/764f75e03306155017e947f39ef2d249697620.debug...
Reading symbols from /usr/lib/debug/.build-id/3b/e3c413536198d0d4f9a7949ab337249d2d00c8.debug...
Reading symbols from /usr/lib/debug/.build-id/ff/e52c76ee590fb51257437e05c5e7c9896f14bd.debug...
Reading symbols from /usr/lib/debug/.build-id/88/ee3f6dec8a95af35dfd7c270f2f45640324a56.debug...
Reading symbols from /usr/lib/debug/.build-id/18/32b2b5ebf443a2d04d220454f36f84634a659f.debug...
Reading symbols from /usr/lib/debug/.build-id/40/c373c863bd204d4ae8dfd116ece3c9a33a1902.debug...
Reading symbols from /usr/lib/debug/.build-id/90/da2440d98dda34506026b5523ea6085c018206.debug...
Reading symbols from /usr/lib/debug/.build-id/2a/cfff9b37bdd8b56636604e8577b4e7f2bd2ae6.debug...
Reading symbols from /usr/lib/debug/.build-id/94/6e8afa9af119368744bfc50fa171090c7eed3a.debug...
Reading symbols from /usr/lib/debug/.build-id/47/34a5ce6b4c111f2e692d8da29a80256351dd42.debug...
Reading symbols from /usr/lib/debug/.build-id/04/609676a1471992e7d173a858f910022b5e341b.debug...
Reading symbols from /usr/lib/debug/.build-id/d3/7f0406b41c8b60b5940a713474ea3412e3b8be.debug...
Reading symbols from /usr/lib/debug/.build-id/8a/b82d91360ecd008f2df683a3ed586116be5963.debug...
Reading symbols from /usr/lib/debug/.build-id/bf/b9d23cca6c037a47091b534cb691c175249538.debug...
Reading symbols from /usr/lib/debug/.build-id/7d/971494207d8faac8917f85ff7a8437f9c9bbce.debug...
Reading symbols from /usr/lib/debug/.build-id/07/d759af57ce22b09384682390c94b4ab7d08c34.debug...
Reading symbols from /usr/lib/debug/.build-id/11/82379cb15c5cd6415b818bd51202df6f9b0c6f.debug...
Reading symbols from /usr/lib/debug/.build-id/04/ec6f769af99bd963bf6621d2b9d2ffd02019a2.debug...
Reading symbols from /usr/lib/debug/.build-id/b5/b79c0c7aaec09eaf4c5f8cfce9488001c61037.debug...
Reading symbols from /usr/lib/debug/.build-id/04/0292353dcf43009e4272a6e6ae7870b4f185e0.debug...
Reading symbols from /usr/lib/debug/.build-id/a6/3bd53f75f94b6390f5624181ae571e6518a100.debug...
Reading symbols from /usr/lib/debug/.build-id/71/150db2e70ddae9146fe6e3e0cac8484ccdbfdd.debug...
Reading symbols from /usr/lib/debug/.build-id/f4/345e2f12286e7091af604cb3a09f366bbca33f.debug...
Reading symbols from /usr/lib/debug/.build-id/9d/3fe4a3abb934da3d21bd9f86278909616b31fb.debug...
Reading symbols from /usr/lib/debug/.build-id/55/483afb7b2d9282238887f30a343ea552f2649e.debug...
Reading symbols from /usr/lib/debug/.build-id/1a/a83db3a2ade11c55a072c774a5b3ae9ddab15a.debug...
Reading symbols from /usr/lib/debug/.build-id/2a/3a84f7f71a8492c471493ca65e985e1240c767.debug...
Reading symbols from /usr/lib/debug/.build-id/09/bf2fd2b7fc9b8d25bc31647754d1463df27f38.debug...
Reading symbols from /usr/lib/debug/.build-id/40/94b0c78b8ef51f5baa5fa230738ffbe8513060.debug...
Reading symbols from /usr/lib/debug/.build-id/ce/0f6f758747a91c4451ee9f410075f535bbaa6f.debug...
Reading symbols from /usr/lib/debug/.build-id/1d/c355e232a1c2862728ebfd1ba5ae8430c1fa4b.debug...
Reading symbols from /usr/lib/debug/.build-id/0e/68cc2df1621b28abb084a17cd7565b40450d1c.debug...
Reading symbols from /usr/lib/debug/.build-id/4f/602e78f17ebe35ecbebe54c077c3b84a4714e5.debug...
Reading symbols from /usr/lib/debug/.build-id/05/ed2d8ff90317d2b3d73a2cb0be9f5fd644e4c6.debug...
Reading symbols from /usr/lib/debug/.build-id/99/bd550166107b93cc0634934864997fbb7024b0.debug...
Reading symbols from /usr/lib/debug/.build-id/dd/a73a1d57b79272c77b534f5d5d7c5af75bf0ef.debug...
Reading symbols from /usr/lib/debug/.build-id/20/9aa192624b486e334c422e2c80533b8cf38bcf.debug...
Reading symbols from /usr/lib/debug/.build-id/c7/e8697b9b2616c2304d46d749e8d15d0998ea24.debug...
Reading symbols from /usr/lib/debug/.build-id/78/766f6333c5ffe749947b7291fb275dc507c424.debug...
Reading symbols from /usr/lib/debug/.build-id/de/7b775b500722c3766bc9c86557a68fa2cf016c.debug...
Reading symbols from /usr/lib/debug/.build-id/ab/320ca39ab752edef306f01e5dcce3806293c75.debug...
Reading symbols from /usr/lib/debug/.build-id/fb/59d6ddc4f81fdde592cf283cd22f8b120a7a8e.debug...
Reading symbols from /usr/lib/debug/.build-id/d1/175374d5b652a1a380548e30b547ceb185665f.debug...
num_cols=3, value_class=Reading symbols from /usr/lib/debug/.build-id/8a/e626d329965f1ddde6c2dc80720a87ea998033.debug...
0x555555886234 "v", row_elements=0x7fffffff9c80) at ./ext/standard/info.c:1299
1299	./ext/standard/info.c: No such file or directory.
(gdb) bt
#0  0x00005555557039f2 in php_info_print_table_row_internal (num_cols=3, value_class=0x555555886234 "v", row_elements=0x7fffffff9c80) at ./ext/standard/info.c:1299
#1  0x0000555555704590 in php_info_print_table_row (num_cols=num_cols@entry=3) at ./ext/standard/info.c:1334
#2  0x00007fffef47cfad in zm_info_http (zend_module=0x555555e4e0f0) at ./build-5.6/src/php_http.c:222
#3  0x00005555557046b0 in _display_module_info_func (module=<optimized out>) at ./ext/standard/info.c:178
#4  0x00005555557b7cd4 in zend_hash_apply (ht=ht@entry=0x7fffffff9df0, apply_func=apply_func@entry=0x5555557046a0 <_display_module_info_func>) at ./Zend/zend_hash.c:641
#5  0x0000555555704f04 in php_print_info (flag=-1) at ./ext/standard/info.c:1071
#6  0x0000555555705872 in zif_phpinfo (ht=<optimized out>, return_value=0x7ffff51f6ae0, return_value_ptr=<optimized out>, this_ptr=<optimized out>, return_value_used=<optimized out>) at ./ext/standard/info.c:1387
#7  0x000055555579a989 in dtrace_execute_internal (execute_data_ptr=<optimized out>, fci=<optimized out>, return_value_used=<optimized out>) at ./Zend/zend_dtrace.c:102
#8  0x0000555555848c30 in zend_do_fcall_common_helper_SPEC (execute_data=0x7ffff51c28d0) at ./Zend/zend_vm_execute.h:560
#9  0x00005555557e7228 in execute_ex (execute_data=execute_data@entry=0x7ffff51c28d0) at ./Zend/zend_vm_execute.h:363
#10 0x000055555579a812 in dtrace_execute_ex (execute_data=0x7ffff51c28d0) at ./Zend/zend_dtrace.c:78
#11 0x00005555557aaadf in zend_execute_scripts (type=type@entry=8, retval=retval@entry=0x0, file_count=file_count@entry=3) at ./Zend/zend.c:1341
#12 0x000055555574b1e0 in php_execute_script (primary_file=primary_file@entry=0x7fffffffc600) at ./main/main.c:2613
#13 0x000055555562b29e in main (argc=<optimized out>, argv=<optimized out>) at ./sapi/fpm/fpm/fpm_main.c:1989
(gdb) 

```

**Comment by oerdnj** [comment]
This might be the same problem as this one: https://github.com/oerdnj/deb.sury.org/issues/1066

What extra modules do you have installed?

**Comment by pschonmann** [comment]
This is php5.6 -m output
```
[PHP Modules]
amqp
bcmath
calendar
Core
ctype
curl
date
dom
ereg
exif
fileinfo
filter
ftp
gd
geoip
gettext
hash
http
iconv
igbinary
imagick
imap
intl
json
ldap
libxml
mbstring
mcrypt
memcached
mhash
msgpack
mysql
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
posix
propro
raphf
readline
Reflection
session
shmop
SimpleXML
soap
sockets
SPL
sqlite3
ssh2
standard
sysvmsg
sysvsem
sysvshm
tidy
tokenizer
wddx
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache
```

**Comment by oerdnj** [comment]
Yep, remove raphf and you should be fine.
