### ISSUE TITLE
add-apt-repository ppa:ondrej/php failing with a bunch of errors

### ISSUE THREAD

**Issue by Trembler34** [oerdnj/deb.sury.org#2036]
**Frequently asked questions**

- [x] I have read [Frequently Asked Questions](https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions)
- [x] I have looked at the list of the existing issues (including closed issues) and searched if my issue has been already reported
- [x] I have tried to resolve the issue myself and will describe what I did in clear and consise manner

Hello,
I am trying to update my php 7.4 to 8.1 for my nextcloud instance using this repository and it keeps failing. I have tried to look through previous issues, using some of the suggested fixes, like adding the LC_ALL UTF-8 infront of the add-apt.. Still can't seem to get around this problem and also adding the locals.

This is on Debian 11

Here is the error.

^CTraceback (most recent call last):
  File "/usr/bin/add-apt-repository", line 168, in <module>
    if not sp.add_source_from_shortcut(shortcut, options.enable_source):
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 737, in add_source_from_shortcut
    worker = self.check_and_add_key_for_whitelisted_shortcut(shortcut)
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 677, in check_and_add_key_for_whitelisted_shortcut
    (srcline, _fname) = shortcut.expand(
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 371, in expand
    codename = get_current_series_from_lp(self._info["distribution"])
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 96, in get_current_series_from_lp
    return os.path.basename(get_info_from_lp(lp_url)["current_series_link"])
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 88, in get_info_from_lp
    return _get_https_content_py3(lp_url)
  File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 102, in _get_https_content_py3
    lp_page = urllib.request.urlopen(request, cafile=LAUNCHPAD_PPA_CERT)
  File "/usr/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.9/urllib/request.py", line 517, in open
    response = self._open(req, data)
  File "/usr/lib/python3.9/urllib/request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 1389, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/usr/lib/python3.9/urllib/request.py", line 1346, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/lib/python3.9/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/usr/lib/python3.9/http/client.py", line 950, in send
    self.connect()
  File "/usr/lib/python3.9/http/client.py", line 1417, in connect
    super().connect()
  File "/usr/lib/python3.9/http/client.py", line 921, in connect
    self.sock = self._create_connection(
  File "/usr/lib/python3.9/socket.py", line 822, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib/python3.9/socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):

Thanks for any direction with this issue..

**Comment by sleemanj** [comment]
From the FAQ which you said you read.https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions#how-to-enable-the-debsuryorg-repositoryTip: Debian is not Ubuntu

**Comment by Trembler34** [comment]
Ive been following some debian guides for updating 7.4 to 8.1 for Nextcloud and they all are showing this repository, apparently not the debian one, not sure why.. That would explain the issue..
