### ISSUE TITLE
[PHP-7] Rasbian/Jessie support

### ISSUE THREAD

**Issue by Jamesking56** [oerdnj/deb.sury.org#256]
Hello,

Really struggling to get PHP 7 working on my Raspberry Pi 2 so I can use it as an automated test runner.

Tried using your sources and I got this error:

````
You are about to add the following PPA to your system:
 Co-installable PHP versions: PHP 5.6, PHP 7.0 and batteries included.

You can get more information about the packages at https://deb.sury.org

For PHP 5.6 use: ppa:ondrej/php5-5.6
For PHP 5.5 use: ppa:ondrej/php5
For PHP 5.4 use: ppa:ondrej/php5-oldstable

BUGS&FEATURES: This PPA now has a issue tracker: https://deb.sury.org/pages/bugreporting.html

PLEASE READ: If you like my work and want to give me a little motivation, please consider donating: https://deb.sury.org/pages/donate.html

WARNING: add-apt-repository is broken with non-UTF-8 locales, see https://github.com/oerdnj/deb.sury.org/issues/56 for workaround:

# apt-get install -y language-pack-en-base
# LC_ALL=en_US.UTF-8 add-apt-repository ppa:ondrej/php
 More info: https://launchpad.net/~ondrej/+archive/ubuntu/php
Press [ENTER] to continue or ctrl-c to cancel adding it

Traceback (most recent call last):
  File "/usr/bin/add-apt-repository", line 167, in <module>
    sp = SoftwareProperties(options=options)
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 105, in __init__
    self.reload_sourceslist()
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 595, in reload_sourceslist
    self.distro.get_sources(self.sourceslist)
  File "/usr/lib/python3/dist-packages/aptsources/distro.py", line 89, in get_sources
    (self.id, self.codename))
aptsources.distro.NoDistroTemplateException: Error: could not find a distribution template for Raspbian/jessie
````

Is it possible to offer Raspbian/Jessie support?

**Comment by oerdnj** [comment]
No, not in the PPAs, they are only for Ubuntu. And I don't have any armhf machines (or at least connected) around to create proper Debian builds, and qemu builds just suck.

**Comment by oerdnj** [comment]
That said - if somebody would prepare a buildd armhf/raspbian machine I could look into integrating it into my PHP build chain.

**Comment by oerdnj** [comment]
Closing the bug now as I don't have any armhf or arm64 builders, so there's nothing I can do for Debian.
