### ISSUE TITLE
PHP 7.1 Segfault in Redis calls when Opcache enabled

### ISSUE THREAD

**Issue by tmwilder** [oerdnj/deb.sury.org#527]
Trying to sort this one out without much luck so far. Under production traffic running under apache with mod php and php7.1 installed from this ppa, we'll see fairly consistent segfaults for a percentage of traffic. Locally on as close an env as possible, nothing seems to reproduce the problem.

I tried to get a min repro by tcpdumping while this happened then pulling the failed endpoint calls via the error logs + pids + lsof, and what I found is that the calls generating the issue did not follow a clear pattern or consistently reproduce the problem.

We get a few different segfaults all with the top level message of ```XXX.c: No such file or directory.```

The issue happens in Redis calls, but also elsewhere. The issue only occurs with Opcache enabled.
```
gdb /usr/sbin/apache2 ./CoreDump
GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.2) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/sbin/apache2...(no debugging symbols found)...done.
[New LWP 4003]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/usr/sbin/apache2 -k start'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  zend_mm_alloc_small (size=<optimized out>, bin_num=<optimized out>, heap=<optimized out>) at /build/php7.1-hzF8RG/php7.1-7.1.0/Zend/zend_alloc.c:1261
1261	/build/php7.1-hzF8RG/php7.1-7.1.0/Zend/zend_alloc.c: No such file or directory.
(gdb) bt full
#0  zend_mm_alloc_small (size=<optimized out>, bin_num=<optimized out>, heap=<optimized out>) at /build/php7.1-hzF8RG/php7.1-7.1.0/Zend/zend_alloc.c:1261
No locals.
#1  zend_mm_alloc_heap (size=<optimized out>, heap=<optimized out>) at /build/php7.1-hzF8RG/php7.1-7.1.0/Zend/zend_alloc.c:1332
        ptr = 0x800000001
#2  _emalloc (size=3, size@entry=32) at /build/php7.1-hzF8RG/php7.1-7.1.0/Zend/zend_alloc.c:2417
No locals.
#3  0x00007f350f036db1 in zend_string_alloc (persistent=<optimized out>, len=4) at /build/php7.1-hzF8RG/php7.1-7.1.0/Zend/zend_string.h:122
        ret = <optimized out>
#4  zend_string_init (persistent=<optimized out>, len=4, str=0x7f350154365a "LLEN") at /build/php7.1-hzF8RG/php7.1-7.1.0/Zend/zend_string.h:158
No locals.
#5  _zend_hash_str_update (ht=ht@entry=0x7f350cb272a0, str=str@entry=0x7f350154365a "LLEN", len=len@entry=4, pData=pData@entry=0x7ffda5397f80) at /build/php7.1-hzF8RG/php7.1-7.1.0/Zend/zend_hash.c:650
        key = 0x7f350154365a
#6  0x00007f350f02cb9f in zend_symtable_str_update (pData=0x7ffda5397f80, len=4, str=0x7f350154365a "LLEN", ht=0x7f350cb272a0) at /build/php7.1-hzF8RG/php7.1-7.1.0/Zend/zend_hash.h:444
        idx = 139865609994241
#7  add_assoc_bool_ex (arg=arg@entry=0x7f350cb6b128, key=key@entry=0x7f350154365a "LLEN", key_len=key_len@entry=4, b=b@entry=1) at /build/php7.1-hzF8RG/php7.1-7.1.0/Zend/zend_API.c:1345
        tmp = {value = {lval = 140727375462480, dval = 6.9528561645413773e-310, counted = 0x7ffda5398050, str = 0x7ffda5398050, arr = 0x7ffda5398050, obj = 0x7ffda5398050, res = 0x7ffda5398050, ref = 0x7ffda5398050, ast = 0x7ffda5398050, zv = 0x7ffda5398050, ptr = 0x7ffda5398050, ce = 0x7ffda5398050, func = 0x7ffda5398050, ww = {w1 = 2772009040, w2 = 32765}},
          u1 = {v = {type = 3 '\003', type_flags = 0 '\000', const_flags = 0 '\000', reserved = 0 '\000'}, type_info = 3}, u2 = {next = 32565, cache_slot = 32565, lineno = 32565, num_args = 32565, fe_pos = 32565, fe_iter_idx = 32565, access_flags = 32565, property_guard = 32565}}
#8  0x00007f350152c77d in ra_init_function_table (ra=ra@entry=0x7f350cb6b0e0) at /build/php-redis-3FeCB6/php-redis-3.1.1~rc1/build-7.1/redis_array_impl.c:124
No locals.
#9  0x00007f350152ca66 in ra_make_array (hosts=0x7f34f8087e30, z_fun=z_fun@entry=0x7ffda5398060, z_dist=z_dist@entry=0x7ffda5398070, hosts_prev=hosts_prev@entry=0x0, b_index=b_index@entry=0 '\000', b_pconnect=b_pconnect@entry=0 '\000', retry_interval=retry_interval@entry=0, b_lazy_connect=0 '\000', connect_timeout=connect_timeout@entry=0.10000000000000001)
    at /build/php-redis-3FeCB6/php-redis-3.1.1~rc1/build-7.1/redis_array_impl.c:366
        i = <optimized out>
        count = <optimized out>
        ra = 0x7f350cb6b0e0
#10 0x00007f350152888c in zim_RedisArray___construct (execute_data=0x7f350ca11bd0, return_value=<optimized out>) at /build/php-redis-3FeCB6/php-redis-3.1.1~rc1/build-7.1/redis_array.c:300
        z0 = 0x7f350ca11c20
        z_fun = {value = {lval = 139865928057552, dval = 6.9102950076939755e-310, counted = 0x7f3512f542d0, str = 0x7f3512f542d0, arr = 0x7f3512f542d0, obj = 0x7f3512f542d0, res = 0x7f3512f542d0, ref = 0x7f3512f542d0, ast = 0x7f3512f542d0, zv = 0x7f3512f542d0, ptr = 0x7f3512f542d0, ce = 0x7f3512f542d0, func = 0x7f3512f542d0, ww = {w1 = 318063312, w2 = 32565}},
          u1 = {v = {type = 1 '\001', type_flags = 0 '\000', const_flags = 0 '\000', reserved = 0 '\000'}, type_info = 1}, u2 = {next = 32565, cache_slot = 32565, lineno = 32565, num_args = 32565, fe_pos = 32565, fe_iter_idx = 32565, access_flags = 32565, property_guard = 32565}}
        z_dist = {value = {lval = 139865466915616, dval = 6.910272224255132e-310, counted = 0x7f34f778cb20, str = 0x7f34f778cb20, arr = 0x7f34f778cb20, obj = 0x7f34f778cb20, res = 0x7f34f778cb20, ref = 0x7f34f778cb20, ast = 0x7f34f778cb20, zv = 0x7f34f778cb20, ptr = 0x7f34f778cb20, ce = 0x7f34f778cb20, func = 0x7f34f778cb20, ww = {w1 = 4151888672,
              w2 = 32564}}, u1 = {v = {type = 1 '\001', type_flags = 0 '\000', const_flags = 0 '\000', reserved = 0 '\000'}, type_info = 1}, u2 = {next = 32565, cache_slot = 32565, lineno = 32565, num_args = 32565, fe_pos = 32565, fe_iter_idx = 32565, access_flags = 32565, property_guard = 32565}}
        zpData = <optimized out>
        z_opts = 0x7f350ca11c30
        ra = 0x0
        b_index = 0 '\000'
        b_autorehash = 0 '\000'
        b_pconnect = 0 '\000'
        hPrev = 0x0
        hOpts = <optimized out>
        l_retry_interval = 0
        b_lazy_connect = <optimized out>
        d_connect_timeout = 0.10000000000000001
#11 0x00007f350f0bfe76 in ZEND_DO_FCALL_SPEC_RETVAL_UNUSED_HANDLER () at /build/php7.1-hzF8RG/php7.1-7.1.0/Zend/zend_vm_execute.h:970
        retval = {value = {lval = 140727375462752, dval = 6.9528561645548159e-310, counted = 0x7ffda5398160, str = 0x7ffda5398160, arr = 0x7ffda5398160, obj = 0x7ffda5398160, res = 0x7ffda5398160, ref = 0x7ffda5398160, ast = 0x7ffda5398160, zv = 0x7ffda5398160, ptr = 0x7ffda5398160, ce = 0x7ffda5398160, func = 0x7ffda5398160, ww = {w1 = 2772009312,
              w2 = 32765}}, u1 = {v = {type = 1 '\001', type_flags = 0 '\000', const_flags = 0 '\000', reserved = 0 '\000'}, type_info = 1}, u2 = {next = 32565, cache_slot = 32565, lineno = 32565, num_args = 32565, fe_pos = 32565, fe_iter_idx = 32565, access_flags = 32565, property_guard = 32565}}
        call = 0x7f350ca11bd0
        fbc = 0x7f3512f54530
        object = <optimized out>
        ret = 0x7ffda53980d0
#12 0x00007f350f06ee7b in execute_ex (ex=<optimized out>) at /build/php7.1-hzF8RG/php7.1-7.1.0/Zend/zend_vm_execute.h:429
        orig_opline = 0x7f351307f5f0
        orig_execute_data = 0x7f350ca11a00
#13 0x00007f3502a50f1b in nr_php_execute_enabled () at /home/hudson/slave-workspace/workspace/php-release-agent/label/centos5-64-nrcamp/agent/php_execute.c:1177
No locals.
#14 0x00007f3502a51562 in nr_php_execute () at /home/hudson/slave-workspace/workspace/php-release-agent/label/centos5-64-nrcamp/agent/php_execute.c:1287
No locals.
#15 0x00007f350f0bf735 in ZEND_DO_FCALL_SPEC_RETVAL_USED_HANDLER () at /build/php7.1-hzF8RG/php7.1-7.1.0/Zend/zend_vm_execute.h:1076
        call = 0x7f350ca11ae0
        fbc = 0x7f350cb0f210
        object = 0x7f350cb0f210
        ret = <optimized out>
#16 0x00007f350f06ee7b in execute_ex (ex=<optimized out>) at /build/php7.1-hzF8RG/php7.1-7.1.0/Zend/zend_vm_execute.h:429
        orig_opline = 0x7f351307f5f0
        orig_execute_data = 0x7f350ca11990
#17 0x00007f3502a50f1b in nr_php_execute_enabled () at /home/hudson/slave-workspace/workspace/php-release-agent/label/centos5-64-nrcamp/agent/php_execute.c:1177
No locals.
#18 0x00007f3502a51562 in nr_php_execute () at /home/hudson/slave-workspace/workspace/php-release-agent/label/centos5-64-nrcamp/agent/php_execute.c:1287
No locals.
#19 0x00007f350f0bf735 in ZEND_DO_FCALL_SPEC_RETVAL_USED_HANDLER () at /build/php7.1-hzF8RG/php7.1-7.1.0/Zend/zend_vm_execute.h:1076
        call = 0x7f350ca11a00
        fbc = 0x7f350cab4978
        object = 0x7f350cab4978
        ret = <optimized out>
#20 0x00007f350f06ee7b in execute_ex (ex=<optimized out>) at /build/php7.1-hzF8RG/php7.1-7.1.0/Zend/zend_vm_execute.h:429
        orig_opline = 0x7f351307f5f0
        orig_execute_data = 0x7f350ca118e0
#21 0x00007f3502a50f1b in nr_php_execute_enabled () at /home/hudson/slave-workspace/workspace/php-release-agent/label/centos5-64-nrcamp/agent/php_execute.c:1177
No locals.
#22 0x00007f3502a51562 in nr_php_execute () at /home/hudson/slave-workspace/workspace/php-release-agent/label/centos5-64-nrcamp/agent/php_execute.c:1287
No locals.
#23 0x00007f350f0bf735 in ZEND_DO_FCALL_SPEC_RETVAL_USED_HANDLER () at /build/php7.1-hzF8RG/php7.1-7.1.0/Zend/zend_vm_execute.h:1076
        call = 0x7f350ca11990
        fbc = 0x7f350caf6ff8
---Type <return> to continue, or q <return> to quit---
        object = 0x7f350caf6ff8
        ret = <optimized out>
#24 0x00007f350f06ee7b in execute_ex (ex=<optimized out>) at /build/php7.1-hzF8RG/php7.1-7.1.0/Zend/zend_vm_execute.h:429
        orig_opline = 0x7f351307f5f0
        orig_execute_data = 0x7f350ca11880
#25 0x00007f3502a50f1b in nr_php_execute_enabled () at /home/hudson/slave-workspace/workspace/php-release-agent/label/centos5-64-nrcamp/agent/php_execute.c:1177
No locals.
#26 0x00007f3502a51562 in nr_php_execute () at /home/hudson/slave-workspace/workspace/php-release-agent/label/centos5-64-nrcamp/agent/php_execute.c:1287
No locals.
#27 0x00007f350f0bf735 in ZEND_DO_FCALL_SPEC_RETVAL_USED_HANDLER () at /build/php7.1-hzF8RG/php7.1-7.1.0/Zend/zend_vm_execute.h:1076
        call = 0x7f350ca118e0
        fbc = 0x7f350cad5518
        object = 0x7f350cad5518
        ret = <optimized out>
#28 0x00007f350f06ee7b in execute_ex (ex=<optimized out>) at /build/php7.1-hzF8RG/php7.1-7.1.0/Zend/zend_vm_execute.h:429
        orig_opline = 0x7f351307f5f0
        orig_execute_data = 0x7f350ca11650
#29 0x00007f3502a50f1b in nr_php_execute_enabled () at /home/hudson/slave-workspace/workspace/php-release-agent/label/centos5-64-nrcamp/agent/php_execute.c:1177
No locals.
#30 0x00007f3502a51562 in nr_php_execute () at /home/hudson/slave-workspace/workspace/php-release-agent/label/centos5-64-nrcamp/agent/php_execute.c:1287
No locals.
#31 0x00007f350f0bf735 in ZEND_DO_FCALL_SPEC_RETVAL_USED_HANDLER () at /build/php7.1-hzF8RG/php7.1-7.1.0/Zend/zend_vm_execute.h:1076
        call = 0x7f350ca11880
        fbc = 0x7f350cad56b8
        object = 0x7f350cad56b8
        ret = <optimized out>
#32 0x00007f350f06ee7b in execute_ex (ex=<optimized out>) at /build/php7.1-hzF8RG/php7.1-7.1.0/Zend/zend_vm_execute.h:429
        orig_opline = 0x7f351307f5f0
        orig_execute_data = 0x7f350ca11440
#33 0x00007f3502a50f1b in nr_php_execute_enabled () at /home/hudson/slave-workspace/workspace/php-release-agent/label/centos5-64-nrcamp/agent/php_execute.c:1177
No locals.
#34 0x00007f3502a51562 in nr_php_execute () at /home/hudson/slave-workspace/workspace/php-release-agent/label/centos5-64-nrcamp/agent/php_execute.c:1287
No locals.
#35 0x00007f350f0bf735 in ZEND_DO_FCALL_SPEC_RETVAL_USED_HANDLER () at /build/php7.1-hzF8RG/php7.1-7.1.0/Zend/zend_vm_execute.h:1076
        call = 0x7f350ca11650
        fbc = 0x7f350cad2d48
        object = 0x7f350cad2d48
        ret = <optimized out>
#36 0x00007f350f06ee7b in execute_ex (ex=<optimized out>) at /build/php7.1-hzF8RG/php7.1-7.1.0/Zend/zend_vm_execute.h:429
        orig_opline = 0x7f351307f5f0
        orig_execute_data = 0x7f350ca11250
#37 0x00007f3502a50f1b in nr_php_execute_enabled () at /home/hudson/slave-workspace/workspace/php-release-agent/label/centos5-64-nrcamp/agent/php_execute.c:1177
No locals.
#38 0x00007f3502a51562 in nr_php_execute () at /home/hudson/slave-workspace/workspace/php-release-agent/label/centos5-64-nrcamp/agent/php_execute.c:1287
No locals.
#39 0x00007f350f0bfbb5 in ZEND_DO_FCALL_SPEC_RETVAL_UNUSED_HANDLER () at /build/php7.1-hzF8RG/php7.1-7.1.0/Zend/zend_vm_execute.h:949
        call = 0x7f350ca11440
        fbc = 0x7f350cad26c8
        object = <optimized out>
        ret = 0x0
#40 0x00007f350f06ee7b in execute_ex (ex=<optimized out>) at /build/php7.1-hzF8RG/php7.1-7.1.0/Zend/zend_vm_execute.h:429
        orig_opline = 0x7f351307f5f0
        orig_execute_data = 0x7f350ca110d0
#41 0x00007f3502a50f1b in nr_php_execute_enabled () at /home/hudson/slave-workspace/workspace/php-release-agent/label/centos5-64-nrcamp/agent/php_execute.c:1177
No locals.
#42 0x00007f3502a51562 in nr_php_execute () at /home/hudson/slave-workspace/workspace/php-release-agent/label/centos5-64-nrcamp/agent/php_execute.c:1287
No locals.
#43 0x00007f350f0bfbb5 in ZEND_DO_FCALL_SPEC_RETVAL_UNUSED_HANDLER () at /build/php7.1-hzF8RG/php7.1-7.1.0/Zend/zend_vm_execute.h:949
        call = 0x7f350ca11250
        fbc = 0x7f350cad25f8
        object = <optimized out>
        ret = 0x0
#44 0x00007f350f06ee7b in execute_ex (ex=<optimized out>) at /build/php7.1-hzF8RG/php7.1-7.1.0/Zend/zend_vm_execute.h:429
        orig_opline = 0x7f3502ce2640 <all_frameworks>
        orig_execute_data = 0x7f3502ce2640 <all_frameworks>
#45 0x00007f3502a5105a in nr_php_execute_file () at /home/hudson/slave-workspace/workspace/php-release-agent/label/centos5-64-nrcamp/agent/php_execute.c:837
No locals.
#46 nr_php_execute_enabled () at /home/hudson/slave-workspace/workspace/php-release-agent/label/centos5-64-nrcamp/agent/php_execute.c:1059
No locals.
#47 0x00007f3502a51562 in nr_php_execute () at /home/hudson/slave-workspace/workspace/php-release-agent/label/centos5-64-nrcamp/agent/php_execute.c:1287
No locals.
#48 0x00007f350f0bc99f in ZEND_INCLUDE_OR_EVAL_SPEC_TMPVAR_HANDLER () at /build/php7.1-hzF8RG/php7.1-7.1.0/Zend/zend_vm_execute.h:51605
        return_value = <optimized out>
        new_op_array = 0x7f350ca870e0
        free_op1 = <optimized out>
        inc_filename = 0x7f350ca110d0
#49 0x00007f350f06ee7b in execute_ex (ex=<optimized out>) at /build/php7.1-hzF8RG/php7.1-7.1.0/Zend/zend_vm_execute.h:429
        orig_opline = 0x7f3502ce2640 <all_frameworks>
        orig_execute_data = 0x7f3502ce2640 <all_frameworks>
#50 0x00007f3502a5105a in nr_php_execute_file () at /home/hudson/slave-workspace/workspace/php-release-agent/label/centos5-64-nrcamp/agent/php_execute.c:837
No locals.
#51 nr_php_execute_enabled () at /home/hudson/slave-workspace/workspace/php-release-agent/label/centos5-64-nrcamp/agent/php_execute.c:1059
---Type <return> to continue, or q <return> to quit---
No locals.
#52 0x00007f3502a51562 in nr_php_execute () at /home/hudson/slave-workspace/workspace/php-release-agent/label/centos5-64-nrcamp/agent/php_execute.c:1287
No locals.
#53 0x00007f350f0c1b94 in zend_execute (op_array=op_array@entry=0x7f350ca87000, return_value=return_value@entry=0x0) at /build/php7.1-hzF8RG/php7.1-7.1.0/Zend/zend_vm_execute.h:474
No locals.
#54 0x00007f350f02a284 in zend_execute_scripts (type=type@entry=8, retval=retval@entry=0x0, file_count=file_count@entry=3) at /build/php7.1-hzF8RG/php7.1-7.1.0/Zend/zend.c:1474
        files = {{gp_offset = 40, fp_offset = 32565, overflow_arg_area = 0x7ffda5398e80, reg_save_area = 0x7ffda5398e10}}
        i = 1
        file_handle = 0x7ffda539b0d0
        op_array = 0x7f350ca87000

#55 0x00007f350efca6c8 in php_execute_script (primary_file=primary_file@entry=0x7ffda539b0d0) at /build/php7.1-hzF8RG/php7.1-7.1.0/main/main.c:2533
        realfile = '\000' <repeats 856 times>...
        __orig_bailout = 0x7ffda539b140
        __bailout = {{__jmpbuf = {139865908461728, -7540880771196452665, 139865908461728, 139865909841824, 0, 139865908630160, -7540880771798335289, -7581740228942167865}, __mask_was_saved = 0, __saved_mask = {__val = {0 <repeats 16 times>}}}}
        prepend_file_p = 0x0
        append_file_p = 0x0
        prepend_file = {handle = {fd = 0, fp = 0x0, stream = {handle = 0x0, isatty = 0, mmap = {len = 0, pos = 0, map = 0x0, buf = 0x0, old_handle = 0x0, old_closer = 0x0}, reader = 0x0, fsizer = 0x0, closer = 0x0}}, filename = 0x0, opened_path = 0x0, type = ZEND_HANDLE_FILENAME, free_filename = 0 '\000'}
        append_file = {handle = {fd = 0, fp = 0x0, stream = {handle = 0x0, isatty = 0, mmap = {len = 0, pos = 0, map = 0x0, buf = 0x0, old_handle = 0x0, old_closer = 0x0}, reader = 0x0, fsizer = 0x0, closer = 0x0}}, filename = 0x0, opened_path = 0x0, type = ZEND_HANDLE_FILENAME, free_filename = 0 '\000'}
        old_cwd = 0x7ffda5398e80 "/"
        retval = 0
#56 0x00007f350f0c3ae2 in php_handler (r=<optimized out>) at /build/php7.1-hzF8RG/php7.1-7.1.0/sapi/apache2handler/sapi_apache2.c:712
        zfd = {handle = {fd = 0, fp = 0x0, stream = {handle = 0x0, isatty = 299306184, mmap = {len = 139865880843079, pos = 139865898034542, map = 0x100000001, buf = 0x0, old_handle = 0x7f3511d65ce0, old_closer = 0x7f3511d70cc8}, reader = 0x7f3511d70cc8, fsizer = 0x7f3511ca40a0, closer = 0x1}},
          filename = 0x7f3511cad598 "/var/deploy/apps/remitlyweb/latest/site/index.php", opened_path = 0x0, type = ZEND_HANDLE_FILENAME, free_filename = 0 '\000'}
        __orig_bailout = 0x0
        __bailout = {{__jmpbuf = {139865908461728, 7539626758952255687, 139865908461728, 139865909841824, 0, 139865908630160, -7540880771198549817, -7581743386317619001}, __mask_was_saved = 0, __saved_mask = {__val = {139865908461728, 0, 139865908462152, 139865909508104, 139865909325472, 139865908501464, 0, 0, 0, 139865908630160, 139865870163107,
                139865909841824, 139865909259368, 0, 139865908461728, 139865909841824}}}}
        ctx = 0x7f3511cadc40
        conf = <optimized out>
        brigade = 0x7f3511caea80
        bucket = <optimized out>
        rv = <optimized out>
        parent_req = 0x0
#57 0x00007f3511bb0be0 in ap_run_handler ()
No symbol table info available.
#58 0x00007f3511bb1129 in ap_invoke_handler ()
No symbol table info available.
#59 0x00007f3511bc66fa in ap_process_async_request ()
No symbol table info available.
#60 0x00007f3511bc69d4 in ap_process_request ()
No symbol table info available.
#61 0x00007f3511bc3472 in ?? ()
No symbol table info available.
#62 0x00007f3511bba250 in ap_run_process_connection ()
No symbol table info available.
#63 0x00007f350da78767 in ?? () from /usr/lib/apache2/modules/mod_mpm_prefork.so
No symbol table info available.
#64 0x00007f350da789a6 in ?? () from /usr/lib/apache2/modules/mod_mpm_prefork.so
No symbol table info available.
#65 0x00007f350da78a06 in ?? () from /usr/lib/apache2/modules/mod_mpm_prefork.so
No symbol table info available.
#66 0x00007f350da796e0 in ?? () from /usr/lib/apache2/modules/mod_mpm_prefork.so
No symbol table info available.
#67 0x00007f3511b978ae in ap_run_mpm ()
No symbol table info available.
#68 0x00007f3511b91046 in main ()
No symbol table info available.
```

The following are installed:

```
apt list | grep php7.1

WARNING: apt does not have a stable CLI interface yet. Use with caution in scripts.

libapache2-mod-php7.1/trusty,now 7.1.0-5+deb.sury.org~trusty+1 amd64 [installed,automatic]
libapache2-mod-php7.1-dbgsym/trusty,now 7.1.0-5+deb.sury.org~trusty+1 amd64 [installed]
libphp7.1-embed/trusty 7.1.0-5+deb.sury.org~trusty+1 amd64
libphp7.1-embed-dbgsym/trusty 7.1.0-5+deb.sury.org~trusty+1 amd64
php7.1/trusty,now 7.1.0-5+deb.sury.org~trusty+1 all [installed]
php7.1-bcmath/trusty,now 7.1.0-5+deb.sury.org~trusty+1 amd64 [installed]
php7.1-bcmath-dbgsym/trusty 7.1.0-5+deb.sury.org~trusty+1 amd64
php7.1-bz2/trusty 7.1.0-5+deb.sury.org~trusty+1 amd64
php7.1-bz2-dbgsym/trusty 7.1.0-5+deb.sury.org~trusty+1 amd64
php7.1-cgi/trusty 7.1.0-5+deb.sury.org~trusty+1 amd64
php7.1-cgi-dbgsym/trusty 7.1.0-5+deb.sury.org~trusty+1 amd64
php7.1-cli/trusty,now 7.1.0-5+deb.sury.org~trusty+1 amd64 [installed]
php7.1-cli-dbgsym/trusty 7.1.0-5+deb.sury.org~trusty+1 amd64
php7.1-common/trusty,now 7.1.0-5+deb.sury.org~trusty+1 amd64 [installed]
php7.1-common-dbgsym/trusty,now 7.1.0-5+deb.sury.org~trusty+1 amd64 [installed]
php7.1-curl/trusty,now 7.1.0-5+deb.sury.org~trusty+1 amd64 [installed]
php7.1-curl-dbgsym/trusty 7.1.0-5+deb.sury.org~trusty+1 amd64
php7.1-dba/trusty 7.1.0-5+deb.sury.org~trusty+1 amd64
php7.1-dba-dbgsym/trusty 7.1.0-5+deb.sury.org~trusty+1 amd64
php7.1-dev/trusty 7.1.0-5+deb.sury.org~trusty+1 amd64
php7.1-enchant/trusty 7.1.0-5+deb.sury.org~trusty+1 amd64
php7.1-enchant-dbgsym/trusty 7.1.0-5+deb.sury.org~trusty+1 amd64
php7.1-fpm/trusty 7.1.0-5+deb.sury.org~trusty+1 amd64
php7.1-fpm-dbgsym/trusty 7.1.0-5+deb.sury.org~trusty+1 amd64
php7.1-gd/trusty 7.1.0-5+deb.sury.org~trusty+1 amd64
php7.1-gd-dbgsym/trusty 7.1.0-5+deb.sury.org~trusty+1 amd64
php7.1-gmp/trusty 7.1.0-5+deb.sury.org~trusty+1 amd64
php7.1-gmp-dbgsym/trusty 7.1.0-5+deb.sury.org~trusty+1 amd64
php7.1-imap/trusty 7.1.0-5+deb.sury.org~trusty+1 amd64
php7.1-imap-dbgsym/trusty 7.1.0-5+deb.sury.org~trusty+1 amd64
php7.1-interbase/trusty 7.1.0-5+deb.sury.org~trusty+1 amd64
php7.1-interbase-dbgsym/trusty 7.1.0-5+deb.sury.org~trusty+1 amd64
php7.1-intl/trusty,now 7.1.0-5+deb.sury.org~trusty+1 amd64 [installed]
php7.1-intl-dbgsym/trusty 7.1.0-5+deb.sury.org~trusty+1 amd64
php7.1-json/trusty,now 7.1.0-5+deb.sury.org~trusty+1 amd64 [installed]
php7.1-json-dbgsym/trusty 7.1.0-5+deb.sury.org~trusty+1 amd64
php7.1-ldap/trusty 7.1.0-5+deb.sury.org~trusty+1 amd64
php7.1-ldap-dbgsym/trusty 7.1.0-5+deb.sury.org~trusty+1 amd64
php7.1-mbstring/trusty,now 7.1.0-5+deb.sury.org~trusty+1 amd64 [installed]
php7.1-mbstring-dbgsym/trusty 7.1.0-5+deb.sury.org~trusty+1 amd64
php7.1-mcrypt/trusty,now 7.1.0-5+deb.sury.org~trusty+1 amd64 [installed]
php7.1-mcrypt-dbgsym/trusty 7.1.0-5+deb.sury.org~trusty+1 amd64
php7.1-mysql/trusty,now 7.1.0-5+deb.sury.org~trusty+1 amd64 [installed]
php7.1-mysql-dbgsym/trusty 7.1.0-5+deb.sury.org~trusty+1 amd64
php7.1-odbc/trusty 7.1.0-5+deb.sury.org~trusty+1 amd64
php7.1-odbc-dbgsym/trusty 7.1.0-5+deb.sury.org~trusty+1 amd64
php7.1-opcache/trusty,now 7.1.0-5+deb.sury.org~trusty+1 amd64 [installed]
php7.1-opcache-dbgsym/trusty,now 7.1.0-5+deb.sury.org~trusty+1 amd64 [installed]
php7.1-pgsql/trusty 7.1.0-5+deb.sury.org~trusty+1 amd64
php7.1-pgsql-dbgsym/trusty 7.1.0-5+deb.sury.org~trusty+1 amd64
php7.1-phpdbg/trusty 7.1.0-5+deb.sury.org~trusty+1 amd64
php7.1-phpdbg-dbgsym/trusty 7.1.0-5+deb.sury.org~trusty+1 amd64
php7.1-pspell/trusty 7.1.0-5+deb.sury.org~trusty+1 amd64
php7.1-pspell-dbgsym/trusty 7.1.0-5+deb.sury.org~trusty+1 amd64
php7.1-readline/trusty,now 7.1.0-5+deb.sury.org~trusty+1 amd64 [installed,automatic]
php7.1-readline-dbgsym/trusty 7.1.0-5+deb.sury.org~trusty+1 amd64
php7.1-recode/trusty 7.1.0-5+deb.sury.org~trusty+1 amd64
php7.1-recode-dbgsym/trusty 7.1.0-5+deb.sury.org~trusty+1 amd64
php7.1-snmp/trusty 7.1.0-5+deb.sury.org~trusty+1 amd64
php7.1-snmp-dbgsym/trusty 7.1.0-5+deb.sury.org~trusty+1 amd64
php7.1-soap/trusty,now 7.1.0-5+deb.sury.org~trusty+1 amd64 [installed]
php7.1-soap-dbgsym/trusty 7.1.0-5+deb.sury.org~trusty+1 amd64
php7.1-sqlite3/trusty,now 7.1.0-5+deb.sury.org~trusty+1 amd64 [installed]
php7.1-sqlite3-dbgsym/trusty 7.1.0-5+deb.sury.org~trusty+1 amd64
php7.1-sybase/trusty 7.1.0-5+deb.sury.org~trusty+1 amd64
php7.1-sybase-dbgsym/trusty 7.1.0-5+deb.sury.org~trusty+1 amd64
php7.1-tidy/trusty 7.1.0-5+deb.sury.org~trusty+1 amd64
php7.1-tidy-dbgsym/trusty 7.1.0-5+deb.sury.org~trusty+1 amd64
php7.1-xml/trusty,now 7.1.0-5+deb.sury.org~trusty+1 amd64 [installed,automatic]
php7.1-xml-dbgsym/trusty 7.1.0-5+deb.sury.org~trusty+1 amd64
php7.1-xmlrpc/trusty,now 7.1.0-5+deb.sury.org~trusty+1 amd64 [installed]
php7.1-xmlrpc-dbgsym/trusty 7.1.0-5+deb.sury.org~trusty+1 amd64
php7.1-xsl/trusty,now 7.1.0-5+deb.sury.org~trusty+1 all [installed]
php7.1-zip/trusty,now 7.1.0-5+deb.sury.org~trusty+1 amd64 [installed]
php7.1-zip-dbgsym/trusty 7.1.0-5+deb.sury.org~trusty+1 amd64```
```

We're on apache 2.4.7 and
```
php -v
PHP 7.1.0-5+deb.sury.org~trusty+1 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.1.0-dev, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.1.0-5+deb.sury.org~trusty+1, Copyright (c) 1999-2016, by Zend Technologies
```

Let me know if I can do anything to help or provide more info, this has been a fairly thorny issue since we were initially very excited to upgrade.

**Comment by oerdnj** [comment]
I have just updated php-redis to 3.1.1RC2. If that doesn't help your only luck would be reporting the issue to the upstream.
(Also 7.1.1 is going to be released tomorrow...)

**Comment by tmwilder** [comment]
@oerdnj - thanks! Your work here is much appreciated. Issue still appears - I've filed an upstream bug.

**Comment by oerdnj** [comment]
@tmwilder Could you post a upstream bug URL here for tracking purposes?

**Comment by tmwilder** [comment]
Sure @oerdnj https://github.com/phpredis/phpredis/issues/1088.

Just encountered an extremely similar issue with the oauth extension and am filing upstream bug there as well, link coming soon.

**Comment by tmwilder** [comment]
Similar Oauth extension issue: https://bugs.php.net/bug.php?id=74030
