### ISSUE TITLE
php-fpm 7.1.5 segfault: zend_mm_alloc_small() at ./Zend/zend_alloc.c

### ISSUE THREAD

**Issue by synner88** [oerdnj/deb.sury.org#612]
Hello, gents

I've been experiencing random segfaults with the latest build of php7.1.5:

```
root@debian ~ # tail /var/log/php-fpm/php-fpm.log
[31-May-2017 11:17:46] WARNING: [pool www] child 23554 exited on signal 11 (SIGSEGV - core dumped) after 125.102748 seconds from start
[31-May-2017 11:19:01] WARNING: [pool www] child 23868 exited on signal 11 (SIGSEGV - core dumped) after 141.054140 seconds from start
[31-May-2017 11:24:23] WARNING: [pool www] child 27228 exited on signal 11 (SIGSEGV - core dumped) after 91.112837 seconds from start
[31-May-2017 11:34:42] WARNING: [pool www] child 31051 exited on signal 11 (SIGSEGV - core dumped) after 75.020310 seconds from start
[31-May-2017 11:35:08] WARNING: [pool www] child 31166 exited on signal 11 (SIGSEGV - core dumped) after 81.394531 seconds from start
[31-May-2017 11:35:57] WARNING: [pool www] child 31507 exited on signal 11 (SIGSEGV - core dumped) after 74.518067 seconds from start

root@debian ~ # lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 8.8 (jessie)
Release:        8.8
Codename:       jessie

root@debian ~ # uname -a
Linux windmill 3.16.0-4-amd64 #1 SMP Debian 3.16.43-2 (2017-04-30) x86_64 GNU/Linux

root@debian ~ # php -m
apc apcu bcmath bz2 calendar Core ctype curl date dom exif fileinfo filter ftp gd gettext hash iconv imagick imap intl json libxml mbstring mcrypt memcached mysqli mysqlnd openssl pcntl pcre PDO pdo_mysql pdo_sqlite Phar posix readline Reflection session shmop SimpleXML snmp sockets SPL sqlite3 standard sysvmsg sysvsem sysvshm tokenizer wddx xml xmlreader xmlwriter xsl Zend OPcache zip zlib

root@debian ~ # gdb /usr/sbin/php-fpm7.1 /tmp/php-fpm-dumps/coredump-php-fpm7.1.23868
GNU gdb (Debian 7.7.1+dfsg-5) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/sbin/php-fpm7.1...Reading symbols from /usr/lib/debug/.build-id/93/5320b22f57f323a309b548fcdb5885ad4e1298.debug...done.
done.
[New LWP 23868]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `php-fpm: pool www                                                            '.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  zend_mm_alloc_small (size=<optimized out>, bin_num=6, heap=0x7f08a7400040) at ./Zend/zend_alloc.c:1261
1261    ./Zend/zend_alloc.c: No such file or directory.
(gdb) bt
#0  zend_mm_alloc_small (size=<optimized out>, bin_num=6, heap=0x7f08a7400040) at ./Zend/zend_alloc.c:1261
#1  zend_mm_alloc_heap (size=<optimized out>, heap=0x7f08a7400040) at ./Zend/zend_alloc.c:1332
#2  zend_mm_realloc_heap (heap=0x7f08a7400040, ptr=0x7f088aa0ac60, size=<optimized out>, copy_size=56) at ./Zend/zend_alloc.c:1610
#3  0x0000000000633d33 in zend_string_extend (persistent=0, len=29, s=0x7f088aa0ac60) at ./Zend/zend_string.h:208
#4  ZEND_CONCAT_SPEC_TMPVAR_TMPVAR_HANDLER () at ./Zend/zend_vm_execute.h:55937
#5  0x0000000000616a9b in execute_ex (ex=<optimized out>) at ./Zend/zend_vm_execute.h:429
#6  0x0000000000673060 in zend_execute (op_array=0x7f08a7478000, op_array@entry=0x7f088c7f1428, return_value=return_value@entry=0x7f08a7413e60) at ./Zend/zend_vm_execute.h:474
#7  0x00000000005cd5a3 in zend_execute_scripts (type=type@entry=8, retval=0x7f08a7413e60, retval@entry=0x0, file_count=file_count@entry=3) at ./Zend/zend.c:1476
#8  0x0000000000569540 in php_execute_script (primary_file=0x7ffd755aeb40) at ./main/main.c:2537
#9  0x0000000000446cb8 in main (argc=13234311, argv=0xc9f059) at ./sapi/fpm/fpm/fpm_main.c:1966
```

I had the same issue with the previous version I used, the 7.1.2 build, I upgraded to the latest in hopes of improvement but no dice.
Please help me pinpoint the root cause?
Thank you in advance!

**Comment by oerdnj** [comment]
This is the kind of issue you need to report to the upstream bug tracker. As there's no issue with the packaging, but with the PHP itself. Please report the url from bugs.php.net here for reference.
