### ISSUE TITLE
Segmentation fault PHP 5.6 FPM

### ISSUE THREAD

**Issue by daim2k5** [oerdnj/deb.sury.org#719]
Hello,
i get this seg fault on a ubuntu xenial server. Any ideas?

PHP 5.6.31-6+ubuntu16.04.1+deb.sury.org+1 (fpm-fcgi)

```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  zend_dtoa (_d=0.74235700000000004, mode=mode@entry=3, ndigits=ndigits@entry=8, decpt=decpt@entry=0x7fffa521f0f4, sign=sign@entry=0x7fffa521f1ec, rve=rve@entry=0x7fffa521f0a0)
    at /build/php5.6-fMzmFi/php5.6-5.6.31/Zend/zend_strtod.c:1454
1454	/build/php5.6-fMzmFi/php5.6-5.6.31/Zend/zend_strtod.c: No such file or directory.
```

```
#0  d2b (_d=0.47993000000000002, e=e@entry=0x7ffca2edc09c, bits=bits@entry=0x7ffca2edc098) at /build/php5.6-fMzmFi/php5.6-5.6.31/Zend/zend_strtod.c:1127
#1  0x00005605393f191d in zend_dtoa (_d=<optimized out>, mode=mode@entry=3, ndigits=ndigits@entry=8, decpt=decpt@entry=0x7ffca2edc164, sign=sign@entry=0x7ffca2edc25c, 
    rve=rve@entry=0x7ffca2edc110) at /build/php5.6-fMzmFi/php5.6-5.6.31/Zend/zend_strtod.c:1536

#2  0x00005605393702f7 in __cvt (value=value@entry=0.47993000000000002, ndigit=ndigit@entry=8, decpt=0x7ffca2edc164, sign=sign@entry=0x7ffca2edc25c, fmode=fmode@entry=1, pad=1)
    at /build/php5.6-fMzmFi/php5.6-5.6.31/main/snprintf.c:96

#3  0x000056053937055e in php_fcvt (sign=0x7ffca2edc25c, decpt=0x7ffca2edc164, ndigit=8, value=0.47993000000000002) at /build/php5.6-fMzmFi/php5.6-5.6.31/main/snprintf.c:138

#4  php_conv_fp (format=<optimized out>, num=0.47993000000000002, add_dp=add_dp@entry=NO, precision=8, dec_point=<optimized out>, is_negative=is_negative@entry=0x7ffca2edc25c, 
    buf=buf@entry=0x7ffca2edc291 "\230\016G\005V", len=0x7ffca2edc254) at /build/php5.6-fMzmFi/php5.6-5.6.31/main/snprintf.c:389

#5  0x00005605393718af in format_converter (odp=odp@entry=0x7ffca2edcae0, fmt=<optimized out>, fmt@entry=0x5605394c7a20 "%.8F %ld", ap=ap@entry=0x7ffca2edcb20)
    at /build/php5.6-fMzmFi/php5.6-5.6.31/main/snprintf.c:1018

#6  0x000056053937221c in strx_printv (ccp=ccp@entry=0x7ffca2edcb1c, buf=buf@entry=0x7ffca2edcc20 "\241U", len=len@entry=100, format=format@entry=0x5605394c7a20 "%.8F %ld", 
    ap=ap@entry=0x7ffca2edcb20) at /build/php5.6-fMzmFi/php5.6-5.6.31/main/snprintf.c:1230

#7  0x0000560539370906 in ap_php_snprintf (buf=buf@entry=0x7ffca2edcc20 "\241U", len=len@entry=100, format=format@entry=0x5605394c7a20 "%.8F %ld")
    at /build/php5.6-fMzmFi/php5.6-5.6.31/main/snprintf.c:1275

#8  0x0000560539331739 in _php_gettimeofday (ht=<optimized out>, return_value=0x56055d275750, mode=<optimized out>, return_value_used=<optimized out>, this_ptr=<optimized out>, 
    return_value_ptr=<optimized out>) at /build/php5.6-fMzmFi/php5.6-5.6.31/ext/standard/microtime.c:86

#9  0x00005605393c2c0a in dtrace_execute_internal (execute_data_ptr=<optimized out>, fci=<optimized out>, return_value_used=<optimized out>)
    at /build/php5.6-fMzmFi/php5.6-5.6.31/Zend/zend_dtrace.c:97
```

On debian with the package
PHP 5.6.31-4+0~20170804100714.6+stretch~1.gbpea630b (fpm-fcgi)
no seg faults :-(

**Comment by oerdnj** [comment]
Do you have a short reproducer?

**Comment by daim2k5** [comment]
Hello,
no its a long running process :-( I try to create one and come back
