### ISSUE TITLE
add-apt-repository -y ppa:ondrej/php

### ISSUE THREAD

**Issue by luizpatrocinio** [oerdnj/deb.sury.org#860]
gpg: keybox '/tmp/tmpyc9bdufw/pubring.gpg' created
gpg: /tmp/tmpyc9bdufw/trustdb.gpg: trustdb created
gpg: key 4F4EA0AAE5267A6C: public key "Launchpad PPA for Ondřej Surý" imported
gpg: Total number processed: 1
gpg:               imported: 1
gpg: no valid OpenPGP data found.

Debian Stretch
LANG="en_US.UTF-8"

**Comment by oerdnj** [comment]
Ubuntu PPAs are for Ubuntu. Use packages.sury.org/php for Debian.

**Comment by YakovL** [comment]
Should I go `add-apt-repository -y ppa:packages.sury.org/php`? I have same errors with `add-apt-repository -y ppa:ondrej/php`; but the command I quoted doesn't work for me as well, gives:

    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 102, in _get_https_content_py3
        lp_page = urllib.request.urlopen(request, cafile=LAUNCHPAD_PPA_CERT)
      File "/usr/lib/python3.5/urllib/request.py", line 163, in urlopen
        return opener.open(url, data, timeout)
      File "/usr/lib/python3.5/urllib/request.py", line 472, in open
        response = meth(req, response)
      File "/usr/lib/python3.5/urllib/request.py", line 582, in http_response
        'http', request, response, code, msg, hdrs)
      File "/usr/lib/python3.5/urllib/request.py", line 510, in error
        return self._call_chain(*args)
      File "/usr/lib/python3.5/urllib/request.py", line 444, in _call_chain
        result = func(*args)
      File "/usr/lib/python3.5/urllib/request.py", line 590, in http_error_default
        raise HTTPError(req.full_url, code, msg, hdrs, fp)
    urllib.error.HTTPError: HTTP Error 404: Not Found
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 327, in get_ppa_info
        ret = get_ppa_info_from_lp(user, ppa)
      File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 92, in get_ppa_info_from_lp
        return get_info_from_lp(lp_url)
      File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 88, in get_info_from_lp
        return _get_https_content_py3(lp_url)
      File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 108, in _get_https_content_py3
        raise PPAException("Error reading %s: %s" % (lp_url, reason), e)
    softwareproperties.ppa.PPAException: 'Error reading https://launchpad.net/api/1.0/~packages.sury.org/+archive/ubuntu/php: Not Found'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 393, in shortcut_handler
        return PPAShortcutHandler(shortcut)
      File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 356, in __init__
        info = get_ppa_info(self.shortcut)
      File "/usr/lib/python3/dist-packages/softwareproperties/ppa.py", line 339, in get_ppa_info
        _get_suggested_ppa_message(user, ppa))
    softwareproperties.shortcuts.ShortcutException: Cannot add PPA: 'ppa:~packages.sury.org/ubuntu/php'.
    ERROR: '~packages.sury.org' user or team does not exist.
    Error: 'ppa:packages.sury.org/php' invalid

According to hosting provider, the system is Debian9 (`uname -a` gives `Linux new 2.6.32-042stab127.2 #1 SMP ... x86_64 GNU/Linux` though)

**Comment by humbertosales** [comment]
curl -sSL https://packages.sury.org/php/README.txt | sudo bash -x
sudo apt update
