### ISSUE TITLE
 http://ppa.launchpad.net/ondrej/php/ubuntu cosmic Release                       404  Not Found

### ISSUE THREAD

**Issue by ranjan-chaurasia05** [oerdnj/deb.sury.org#904]
sudo apt-add-repository ppa:ondrej/php
Traceback (most recent call last):
  File "/usr/bin/lsb_release", line 98, in <module>
    main()
  File "/usr/bin/lsb_release", line 62, in main
    distinfo = lsb_release.get_distro_information(options.upstream)
  File "/usr/lib/python3/dist-packages/lsb_release.py", line 344, in get_distro_information
    distinfo = guess_debian_release()
  File "/usr/lib/python3/dist-packages/lsb_release.py", line 239, in guess_debian_release
    get_distro_info(distinfo['ID'])
  File "/usr/lib/python3/dist-packages/lsb_release.py", line 41, in get_distro_info
    RELEASES_ORDER.sort(key=lambda n: float(n[0]))
  File "/usr/lib/python3/dist-packages/lsb_release.py", line 41, in <lambda>
    RELEASES_ORDER.sort(key=lambda n: float(n[0]))
ValueError: could not convert string to float: '12.04 LTS'
Traceback (most recent call last):
  File "/usr/bin/lsb_release", line 98, in <module>
    main()
  File "/usr/bin/lsb_release", line 62, in main
    distinfo = lsb_release.get_distro_information(options.upstream)
  File "/usr/lib/python3/dist-packages/lsb_release.py", line 344, in get_distro_information
    distinfo = guess_debian_release()
  File "/usr/lib/python3/dist-packages/lsb_release.py", line 239, in guess_debian_release
    get_distro_info(distinfo['ID'])
  File "/usr/lib/python3/dist-packages/lsb_release.py", line 41, in get_distro_info
    RELEASES_ORDER.sort(key=lambda n: float(n[0]))
  File "/usr/lib/python3/dist-packages/lsb_release.py", line 41, in <lambda>
    RELEASES_ORDER.sort(key=lambda n: float(n[0]))
ValueError: could not convert string to float: '16.04 LTS'
Traceback (most recent call last):
  File "/usr/bin/lsb_release", line 98, in <module>
    main()
  File "/usr/bin/lsb_release", line 62, in main
    distinfo = lsb_release.get_distro_information(options.upstream)
  File "/usr/lib/python3/dist-packages/lsb_release.py", line 344, in get_distro_information
    distinfo = guess_debian_release()
  File "/usr/lib/python3/dist-packages/lsb_release.py", line 239, in guess_debian_release
    get_distro_info(distinfo['ID'])
  File "/usr/lib/python3/dist-packages/lsb_release.py", line 41, in get_distro_info
    RELEASES_ORDER.sort(key=lambda n: float(n[0]))
  File "/usr/lib/python3/dist-packages/lsb_release.py", line 41, in <lambda>
    RELEASES_ORDER.sort(key=lambda n: float(n[0]))
ValueError: could not convert string to float: '12.04 LTS'
 Co-installable PHP versions: PHP 5.6, PHP 7.x and most requested extensions are included. Only Supported Versions of PHP (http://php.net/supported-versions.php) for Supported Ubuntu Releases (https://wiki.ubuntu.com/Releases) are provided. Don't ask for end-of-life PHP versions or Ubuntu release, they won't be provided.

Debian oldstable and stable packages are provided as well: https://deb.sury.org/#debian-dpa

You can get more information about the packages at https://deb.sury.org

BUGS&FEATURES: This PPA now has a issue tracker:
https://deb.sury.org/#bug-reporting

CAVEATS:
1. If you are using php-gearman, you need to add ppa:ondrej/pkg-gearman
2. If you are using apache2, you are advised to add ppa:ondrej/apache2
3. If you are using nginx, you are advise to add ppa:ondrej/nginx-mainline
   or ppa:ondrej/nginx

PLEASE READ: If you like my work and want to give me a little motivation, please consider donating regularly: https://donate.sury.org/

WARNING: add-apt-repository is broken with non-UTF-8 locales, see 
https://github.com/oerdnj/deb.sury.org/issues/56 for workaround:

# LC_ALL=C.UTF-8 add-apt-repository ppa:ondrej/php
 More info: https://launchpad.net/~ondrej/+archive/ubuntu/php
Press [ENTER] to continue or ctrl-c to cancel adding it

**Comment by oerdnj** [comment]
Wait for at least rc1
